"""align_maintenance_requests_to_wire_format

Revision ID: e26eaa5a5b5e
Revises: 46339d7c2ae3
Create Date: 2026-06-01 13:43:32.207800

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e26eaa5a5b5e"
down_revision: str | None = "46339d7c2ae3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maintenance_requests", sa.Column("title", sa.String(length=80), nullable=True))
    op.add_column("maintenance_requests", sa.Column("summary", sa.Text(), nullable=False))
    op.add_column("maintenance_requests", sa.Column("assignee_id", sa.String(), nullable=True))
    op.add_column(
        "maintenance_requests", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.drop_column("maintenance_requests", "description")
    op.drop_column("maintenance_requests", "photo_url")
    op.drop_column("maintenance_requests", "timeline")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "maintenance_requests",
        sa.Column(
            "timeline", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "maintenance_requests",
        sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "maintenance_requests",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("maintenance_requests", "updated_at")
    op.drop_column("maintenance_requests", "assignee_id")
    op.drop_column("maintenance_requests", "summary")
    op.drop_column("maintenance_requests", "title")
    # ### end Alembic commands ###
